runtime: python39 


handlers:
- url: /(.*)
  static_files: /\1
  upload: (.*)
  
- url: /index.html
  static_files: index.html
  upload: index.html
  
- url: /.png
  static_files: "https://storage.cloud.google.com/profil_ku/foto%20bangkit.PNG"
  upload: "https://storage.cloud.google.com/profil_ku/foto%20bangkit.PNG"
